### ISSUE TITLE
npm run `lint` errors

### ISSUE THREAD

**Issue by jasonLaster** [gaearon/redux-devtools#197]
This could easily be my setup (npm v3.3.6) (node 5.0.0). It could also be another dependency that's out of date...

```
> redux-devtools@2.1.5 prepublish /Users/jlaster/src/_os/_js/react/redux-devtools
> npm run lint && npm run test && npm run clean && npm run build


> redux-devtools@2.1.5 lint /Users/jlaster/src/_os/_js/react/redux-devtools
> eslint src test examples

/Users/jlaster/src/_os/_js/react/redux-devtools/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:70
        if (node == null) {
                 ^
RangeError: Maximum call stack size exceeded
    at keys (native)
    at Referencer.Visitor.visitChildren (/Users/jlaster/src/_os/_js/react/redux-devtools/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:78:24)
    at Referencer.Visitor.visit (/Users/jlaster/src/_os/_js/react/redux-devtools/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:112:14)
    at Referencer.Visitor.visitChildren (/Users/jlaster/src/_os/_js/react/redux-devtools/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:93:26)
    at Referencer.Visitor.visit (/Users/jlaster/src/_os/_js/react/redux-devtools/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:112:14)
    at Referencer.Visitor.visitChildren (/Users/jlaster/src/_os/_js/react/redux-devtools/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:88:38)
    at Referencer.Visitor.visit (/Users/jlaster/src/_os/_js/react/redux-devtools/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:112:14)
    at Referencer.Visitor.visitChildren (/Users/jlaster/src/_os/_js/react/redux-devtools/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:93:26)
    at Referencer.Visitor.visit (/Users/jlaster/src/_os/_js/react/redux-devtools/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:112:14)
    at Referencer.Visitor.visitChildren (/Users/jlaster/src/_os/_js/react/redux-devtools/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:88:38)
```

**Comment by ellbee** [comment]
I can't reproduce this with node 5 and a fresh node_modules folder.

For what its worth, I have seen this error before. It was occurring on the `react-redux` CI server, and the fix there was to move from iojs v2 to node 5.

**Comment by jasonLaster** [comment]
Thanks @ellbee.
