### ISSUE TITLE
Module build failed: ReferenceError: Unknown plugin "transform-decorators-legacy"

### ISSUE THREAD

**Issue by iamvijaydev** [gaearon/redux-devtools#355]
I getting the following error when tried to integrate as per [walkthrough](https://github.com/gaearon/redux-devtools/blob/master/docs/Walkthrough.md). Any help is much appreciated. Thanks in advance.

```javascript
ERROR in ./~/react-json-tree/lib/index.js
Module build failed: ReferenceError: Unknown plugin "transform-decorators-legacy" specified in "<path-removed-for-protection>\\node_modules\\react-json-tree\\.babelrc" at 0, attempted to resolve relative to "<path-removed-for-protection>\\node_modules\\react-json-tree"
    at <path-removed-for-protection>\node_modules\babel-core\lib\transformation\file\options\option-manager.js:180:17
    at Array.map (native)
    at Function.normalisePlugins (<path-removed-for-protection>\node_modules\babel-core\lib\transformation\file\options\option-manager.js:158:20)
    at OptionManager.mergeOptions (<path-removed-for-protection>\node_modules\babel-core\lib\transformation\file\options\option-manager.js:234:36)
    at OptionManager.init (<path-removed-for-protection>\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (<path-removed-for-protection>\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (<path-removed-for-protection>\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (<path-removed-for-protection>\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (<path-removed-for-protection>\node_modules\babel-loader\lib\index.js:46:20)
    at Object.module.exports (<path-removed-for-protection>\node_modules\babel-loader\lib\index.js:155:20)
 @ ./~/redux-devtools-log-monitor/lib/LogMonitorEntry.js 27:21-47
 @ ./~/redux-devtools-log-monitor/lib/LogMonitorEntryList.js
 @ ./~/redux-devtools-log-monitor/lib/LogMonitor.js
 @ ./~/redux-devtools-log-monitor/lib/index.js
 @ ./src/containers/devTools/index.jsx
 @ ./src/containers/root/Root.dev.js
 @ ./src/containers/root/index.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:3000 webpack/hot/dev-server react-hot-loader/patch webpack-dev-server/client?http://localhost:3000 webpack/hot/only-dev-server ./src/index.js
```

**Comment by iamvijaydev** [comment]
I made a silly mistake in my webpack configuration. I forgot to exclude `/node_modules/` from processing of `/\.(js|jsx)$/` files. For more please read [here](https://github.com/gaearon/redux-devtools/issues/259#issuecomment-194943953).
