### ISSUE TITLE
Devtools throwing an error

### ISSUE THREAD

**Issue by kolodny** [gaearon/redux-devtools#94]
Here's the relevant code, When I shut down my mock server, and try to delete a user twice

```js

//actions
export const deleteUser = user => (dispatch, getState) => {
  const { api } = getState();

  dispatch({
    type: DELETE_USER,
    payload: {
      user,
    },
  });

  return (async () => {
    try {
      await api.post('/user/delete', {uuid: user.uuid});
      return dispatch(deletedUserOk(user));
    } catch (err) {
      return dispatch(deletedUserFail(err));
    }
  })();


};

export const deletedUserOk = user => ({
  type: DELETED_USER_OK,
  payload: { user },
});
export const deletedUserFail = error => ({
  type: DELETED_USER_FAIL,
  error: true,
  payload: error,
});


//reducers


  [DELETE_USER](state, action) {
    const { user } = action.payload;

    const index = state.users.indexOf(user);

    return update(state, {
      users: {
        [index]: {
          deleting: {$set: true},
        },
      },
    });
  },

  [DELETED_USER_OK](state, action) {
    const { user } = action.payload;

    const find = user => {
      for (let u of state.users) {
        if (u.uuid === user.uuid) {
          return u;
        }
      }
    };

  

```

I don't have a reducer for `DELETED_USER_FAIL` but I don't see how that would matter. This is the error message:

```
TypeError: Cannot read property 'deleting' of undefined
    at update (eval at <anonymous> (http://localhost:3000/static/bundle.js:4724:2), <anonymous>:160:34)
    at update (eval at <anonymous> (http://localhost:3000/static/bundle.js:4724:2), <anonymous>:160:22)
    at update (eval at <anonymous> (http://localhost:3000/static/bundle.js:4724:2), <anonymous>:160:22)
    at Object._refluxCreateReducer.createReducer._createReducer.(anonymous function) [as DELETE_USER] (eval at <anonymous> (http://localhost:3000/static/bundle.js:4736:2), <anonymous>:47:10)
    at reducer (eval at <anonymous> (http://localhost:3000/static/bundle.js:4622:2), <anonymous>:6:35)
    at eval (eval at <anonymous> (http://localhost:3000/static/bundle.js:2294:2), <anonymous>:94:22)
    at eval (eval at <anonymous> (http://localhost:3000/static/bundle.js:2300:2), <anonymous>:15:19)
    at Array.reduce (native)
    at Object.mapValues [as default] (eval at <anonymous> (http://localhost:3000/static/bundle.js:2300:2), <anonymous>:14:27)
    at combination (eval at <anonymous> (http://localhost:3000/static/bundle.js:2294:2), <anonymous>:93:49)
```

Ok so it seems that not returning a new identical object fixes this, ie:

```js
[DELETE_USER](state, action) {
    const { user } = action.payload;

    if (user.deleting) {
      return state;
    }

    const index = state.users.indexOf(user);

    return update(state, {
      users: {
        [index]: {
          deleting: {$set: true},
        },
      },
    });
  },
```

**Comment by gaearon** [comment]
To be honest this report is hard to understand, and even harder to correlate its relation to DevTools. Does it work with DevTools disabled? What exactly do you mock and why do you call delete twice? How do you compose those action-specific reducers into a single reducer?

The only way we can help you is if you provide a sample project reproducing a problem, so that we could run and see what went wrong. Otherwise it's very vague.
